# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-stretch-node

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "front-end/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline
      - run: cd front-end && npm install

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "front-end/package.json" }}

      - run: mvn package
      - run: cd front-end && npm test

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/


  deploy:
    docker:
      - image: circleci/python:stretch

    working_directory: ~/repo

    steps:
      - run: sudo pip install awsebcli
      - run: eb create memento-dev -r eu-central-1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
              - build